#!/bin/sh
mkdir -p /home/dsdeur/webapps/rwu/run
pid=$(/sbin/pidof /home/dsdeur/webapps/rwu/bin/node)
if echo "$pid" | grep -q " "; then
  pid=""
fi
if [ -n "$pid" ]; then
  user=$(ps -p $pid -o user | tail -n 1)
  if [ $user = "dsdeur" ]; then
    exit 0
  fi
fi
nohup /home/dsdeur/webapps/rwu/bin/node /home/dsdeur/webapps/rwu/app.js > /dev/null 2>&1 &
/sbin/pidof /home/dsdeur/webapps/rwu/bin/node > /home/dsdeur/webapps/rwu/run/node.pid
